# Generated by Django 4.2.4 on 2023-12-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='childrens_menu',
            field=models.PositiveIntegerField(max_length=20, verbose_name='Cantidad de Menús Infantiles'),
        ),
    ]
