# Generated by Django 4.2.5 on 2023-09-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typepay',
            name='type_pay',
            field=models.CharField(max_length=100, verbose_name='Tipo de pago'),
        ),
    ]
