# Generated by Django 4.2.4 on 2023-12-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombres Completos'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='special_need',
            field=models.CharField(choices=[('Campo_silla_de_redas', 'Campo silla de redas'), ('Comunicador_de_lenguaje_de_señas ', 'Comunicador de lenguaje de señas '), ('Ninguno', 'Ninguno')], default='Campo_silla_de_redas', max_length=200, verbose_name='Necesidad especial'),
        ),
    ]
