# Generated by Django 4.2.4 on 2023-09-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statepqrsd',
            options={'ordering': ['id'], 'verbose_name': 'Estado pqrsd', 'verbose_name_plural': 'Estados pqrsd'},
        ),
        migrations.RemoveField(
            model_name='statepqrsd',
            name='StatePqrsd',
        ),
        migrations.AddField(
            model_name='statepqrsd',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterModelTable(
            name='statepqrsd',
            table='estado_pqrsd',
        ),
    ]
