# Generated by Django 4.2.4 on 2023-10-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='event_date',
            field=models.DateField(verbose_name='Fecha de evento'),
        ),
    ]
