# Generated by Django 4.2.4 on 2023-09-03 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Ingrediete',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'Ingredientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
                ('Ingrediente', models.ManyToManyField(to='core.ingrediente')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
                'db_table': 'Pizza',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='rent',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='real_estate',
        ),
        migrations.DeleteModel(
            name='RealEstate',
        ),
        migrations.AlterField(
            model_name='pay',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pizza'),
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
