# Generated by Django 4.2.4 on 2023-09-03 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingrediente_pizza_remove_rent_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_catering', models.CharField(max_length=20, verbose_name='nombre del menu')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'db_table': 'Menú',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_decor', models.CharField(max_length=20, verbose_name='nombre de la decoracion')),
            ],
            options={
                'verbose_name': 'Decoracion',
                'verbose_name_plural': 'Decoraciones',
                'db_table': 'Decoracion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_menaje', models.CharField(max_length=20, verbose_name='nombre del menaje')),
            ],
            options={
                'verbose_name': 'Menaje',
                'verbose_name_plural': 'Menajes',
                'db_table': 'Menaje',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Phone', models.PositiveIntegerField(verbose_name='Telefono')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Date', models.DateField(verbose_name='Fecha')),
                ('Hour', models.TimeField(verbose_name='Hora')),
                ('Catering', models.ManyToManyField(to='core.catering')),
                ('Decor', models.ManyToManyField(to='core.decor')),
                ('Menaje', models.ManyToManyField(to='core.menaje')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
                'db_table': 'Alquiler',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.AlterField(
            model_name='pay',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rent'),
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
