# Generated by Django 4.2.4 on 2023-12-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cotizacion_childrens_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='special_need',
            field=models.CharField(default='Campo_silla_de_redas', max_length=200, verbose_name='Necesidad especial'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='theme',
            field=models.CharField(default='Mariposas', max_length=200, verbose_name='Tematica'),
        ),
    ]
