# Generated by Django 5.0 on 2023-12-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
