# Generated by Django 4.2.4 on 2023-09-24 03:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_loyalty_filing_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='filing_number',
            field=models.PositiveIntegerField(default=core.models.generate_random_radicado, verbose_name='Número de radicado'),
        ),
    ]
