# Generated by Django 4.2.4 on 2023-08-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campus_customer_drinks_eventtype_inventory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['id'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelTable(
            name='campus',
            table='sed',
        ),
    ]
