# Generated by Django 4.2.4 on 2023-09-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statepqrsd_loyalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statepqrsd',
            name='loyalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loyalty'),
        ),
    ]
