# Generated by Django 5.0 on 2023-12-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pqrs_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='childrens_menu',
            field=models.PositiveIntegerField(verbose_name='Cantidad de Menús Infantiles'),
        ),
    ]
