# Generated by Django 4.2.4 on 2023-09-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_statepqrsd_loyalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statepqrsd',
            name='loyalty',
        ),
    ]
