# Generated by Django 5.0 on 2023-12-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cotizacion_childrens_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PQRS',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='childrens_menu',
            field=models.PositiveIntegerField(max_length=20, verbose_name='Cantidad de Menús Infantiles'),
        ),
    ]
