# Generated by Django 4.2.4 on 2023-09-24 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_statepqrsd_loyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='statepqrsd',
            name='loyalty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loyalty'),
        ),
    ]
