# Generated by Django 4.2.4 on 2023-09-24 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_statepqrsd_loyalty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stateproduct',
            options={'ordering': ['id'], 'verbose_name': 'Estado Producto', 'verbose_name_plural': 'Estados productos'},
        ),
        migrations.RemoveField(
            model_name='stateproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='stateproduct',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='stateproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stateproduct',
            name='idle',
        ),
        migrations.AddField(
            model_name='stateproduct',
            name='estadoP',
            field=models.CharField(choices=[('Activo ', 'Activo '), ('Inactivo ', 'Inactivo ')], default='Activo ', max_length=20),
        ),
        migrations.AlterField(
            model_name='stateproduct',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
        migrations.AlterModelTable(
            name='stateproduct',
            table='estado_producto',
        ),
    ]
