# Generated by Django 4.2.4 on 2023-09-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_stateproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='guest_document',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='type_pay',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='campus',
            field=models.CharField(max_length=200, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='eventType',
            field=models.CharField(max_length=200, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='gender',
            field=models.CharField(max_length=30, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='lounge',
            field=models.CharField(max_length=200, verbose_name='Salón'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='theme',
            field=models.CharField(choices=[('Campestre', 'Campestre'), ('Neon', 'Neon'), ('Alfombra_Roja', 'Alfombra Roja'), ('Personaje_Disney', 'Personaje Disney'), ('Flores', 'Flores'), ('Noche_estrellas', 'Noche de Estrellas'), ('Tropical', 'Tropical'), ('Mariposas', 'Mariposas')], default='Mari´posas', max_length=200, verbose_name='Tematica'),
        ),
    ]
