# Generated by Django 4.2.4 on 2023-11-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reserva_event_date'),
        ('core', '0002_alter_typepay_type_pay'),
        ('core', '0002_carrito_delete_rent_alter_statepqrsd_options_and_more'),
        ('core', '0002_cotizacion'),
        ('core', '0003_alter_loyalty_filing_number'),
        ('core', '0003_carrito_delete_rent_alter_statepqrsd_options_and_more'),
        ('core', '0008_remove_reserva_guest_document_and_more'),
    ]

    operations = [
    ]
